### ISSUE TITLE
After setting the build target to ECMAScript 5, getters are still underlined as errors

### ISSUE THREAD

**Issue by stubailo** [palantir/eclipse-typescript#15]
I've set the build target to ES5, but it still says "Accessors are only available when targeting ECMAScript 5 or higher."

**Comment by Rouche** [comment]
Is this bug fixed? I am getting this error on version 1.7.0.v20151201-1631	com.palantir.typescript.feature.feature.group	Palantir Technologies, Inc.
I am set on target ES6

Or is there a workaround? Weird because the file is correctly compiled to .js.

Thanks.

**Comment by derekcicerone** [comment]
This should be fixed. What does the error message look like?

**Comment by Rouche** [comment]
Accessors are only available when targeting ECMAScript 5 and higher.

**Comment by derekcicerone** [comment]
I just tried this and I'm unable to reproduce the issue. Are you sure you are using the latest plugin and the ECMA version is set to 5 or later? You might want to try rebooting Eclipse as well.

**Comment by Rouche** [comment]
This is definatelly weird. We tryed targetting ES5 and ES6 without success.

All our devs have the same problem. We are on the eclipse Mars.1 (4.5.1) Java Developpers 64bit.

Do you want me to zip our version and put it on drive?

**Comment by derekcicerone** [comment]
Can you check in the plugins folder and verify you have the latest version of the plugin? Someone else recently hit issues that didn't seem possible with the latest release and it turned out they have an older version of the plugin hanging around.

**Comment by Rouche** [comment]
Ok, i will check all this (tomorrow).

**Comment by Rouche** [comment]
We did had an old 1.5.0 version lying in pusings but.... there was a project settings override. 

I feel bad, very sorry to have made you loose time. 

Thanks.

**Comment by derekcicerone** [comment]
Cool, no worries, glad you figured it out!
