### ISSUE TITLE
How to compile .ts files

### ISSUE THREAD

**Issue by CiaranMcCann** [palantir/eclipse-typescript#21]
I'm also have the same issue as #20 

I have installed the plugin and it works fine for in terms of editing, auto complete etc. 
Though it doesn't complie on save or when I call build on the project. There isn't any complie on save option in the GUI as you see below in the screenshots? I just installed it today.

I can compile the main.ts file from the command line no problem. When I save or try build project a progress bar pops up and then nothing. No errors or output at all in the console window. Also just to note, I wasn't sure what type the project had to be, general project, web, javascript? Or does it matter?

System 
- Mac OSX
- Kepler release of Eclipse Java EE IDE for Web Developers.
- node v0.10.13
- tsc 0.9.0.1

Below are two screen shots 

![screen shot 2013-08-17 at 15 56 13](https://f.cloud.github.com/assets/705554/981205/76c46aee-074d-11e3-9f32-97b5f5794ef8.png)

![screen shot 2013-08-17 at 15 57 18](https://f.cloud.github.com/assets/705554/981206/76db91b0-074d-11e3-8239-634b33037466.png)

Plus one @Sergio-Mira

**Comment by divagartech** [comment]
hi same issue is still in ubuntu willy
