### ISSUE TITLE
How to solve an error message "Cannot compile external modules..." when using export keyword

### ISSUE THREAD

**Issue by stan0227** [palantir/eclipse-typescript#220]
When using "export" keyword, an error message "Cannot compile external modules unless the '--module' flag is provided." will arise.

I know that it is a typescript compiler error message for notifying user using "--module" flag to build source code. But how to disable this error message when editing?

**Comment by derekcicerone** [comment]
You can change the module type in the project settings.

**Comment by stan0227** [comment]
Hi derekcicerone,

Do you mean that the project settings is the below screenshot?
![project_setting](https://cloud.githubusercontent.com/assets/2187097/5821089/7d2b19d0-a104-11e4-83d0-0ad92b624791.jpg)

**Comment by derekcicerone** [comment]
Yup, exactly.
