### ISSUE TITLE
Can expand number of characters of "Auto Activation Trigger"?

### ISSUE THREAD

**Issue by stan0227** [palantir/eclipse-typescript#221]
The current number of characters of "Auto Activation Trigger" is just 4 char.

Is it possible to expand the number of characters?

**Comment by derekcicerone** [comment]
Sorry, I'm not sure what this means.

**Comment by stan0227** [comment]
Sorry for I press the Comment button when I still editing this issue.

**Comment by stan0227** [comment]
Hi derekcicerone, could you check this issue again? Sorry for my carelessness.

**Comment by derekcicerone** [comment]
What is "Auto activation trigger"? A screenshot would be helpful if it's relevent.

**Comment by stan0227** [comment]
![auto_activation_triggers](https://cloud.githubusercontent.com/assets/2187097/5820079/8905473c-a0fd-11e4-9115-f3aa42824141.jpg)

Windows > Preferences > Typescript > Content Assist

**Comment by derekcicerone** [comment]
How many characters do you want to be able to enter? Just curious: why would you want chars other than "."?

**Comment by stan0227** [comment]
Hi derekcicerone,

I am a new user for eclipse editor. I usually using Visual Studio, Nodepad++, and Brackets. When I type some variables in a scope or keyword, these editors will automatically show the suggestion list. But in eclipse editor, the default trigger action is using "CTRL + SPACE". I survey the work around method to solve this problem, just like http://stackoverflow.com/questions/6202223/auto-code-completion-on-eclipse/6203060#6203060

In the survey, they types ".abcdefghijklmnopqrstuvwxyz_" in the input box of "auto activation triggers" of JAVA Setting. So I think maybe it may also working in the typescript plugin.

**Comment by derekcicerone** [comment]
Ok, just pushed a fix to the mainline release. Please try it out and let me know if it resolves the issue.

**Comment by stan0227** [comment]
Yes! It can work! Thanks a lot.
