### ISSUE TITLE
Better coloring for template strings

### ISSUE THREAD

**Issue by mihhail-lapushkin** [palantir/eclipse-typescript#222]
With the current coloring the string part blends with the code. Would be great to color string parts in the same color as strings. This also goes for the color of backticks.

**Comment by derekcicerone** [comment]
Yeah, I've flagged this concern with the TypeScript devs (https://github.com/Microsoft/TypeScript/issues/1477#issuecomment-66903243) but I'm not sure what more we can do. It sounds like they have better support coming in 1.5 or possibly 1.6.
