### ISSUE TITLE
Multiple Projects within single git repository

### ISSUE THREAD

**Issue by Palmer-JC** [palantir/eclipse-typescript#224]
Hi,
I am working in a repository, hosted on GITHUB.  I have no control here to make multiple repositories.  

Originally, I only had one output, so I made a general project at the top of the repository.  I realized that part of what I was doing could be split out.  Switched to 2 projects, at the directory level which they start.   I deleted the old .project file @ the repository level.

The Git part worked fine from either project, except that commits / fetches / merges  worked on the whole repository.  No big deal.

The project which became the broken out subset builds fine.  I copy its d.ts to a directory in the larger project.  When I try to build the larger project there is a quick flash in the bottom right, but nothing is ever built.

Is there any audit trail inside of Eclipse?  Nothing is written anywhere (Am used to Ant inside of Netbeans).  I made an non-repository project of this and it builds fine.  Could then copy output to repository version, but a error prone kludge.

**Comment by derekcicerone** [comment]
Each project needs to be configured for TypeScript separately. Perhaps only one of the projects is configured to build via TypeScript?

**Comment by Palmer-JC** [comment]
Typescript is listed as a builder for the project, and also has a section in project properties.

**Comment by derekcicerone** [comment]
That just enabled TS for the project but doesn't turn on the build-on-save support. That needs to be enabled via the UI explicitly.

**Comment by Palmer-JC** [comment]
Was not doing auto build.  Just tried deleting the other project (not the files).  Reloaded, but no build.  Is nothing ever written to some "console" during a build?

**Comment by derekcicerone** [comment]
Nothing is written to the console during a build.

**Comment by derekcicerone** [comment]
Could you share a screenshot of your projects' TypeScript settings?

**Comment by Palmer-JC** [comment]
Easier to get everything on one shot to list the .prefs file.  I actually listed the non-repository version right afterward to make sure they were the same.
![typescript prefs](https://cloud.githubusercontent.com/assets/7916131/6030392/28930b78-abc5-11e4-9566-711428862985.png)

**Comment by derekcicerone** [comment]
Oh I think I might see an issue: you've specified asynchronous modules but single file outputs. Those aren't compatible with one another (AMD modules need to be output to individual files). Wanna try removing the output file or changing to a different module type?

**Comment by Palmer-JC** [comment]
This is what I have been doing for a while.  Code is going to run in a browser, not server.  Played anyway. Could never get repository to write a single file, regardless of module type, & also changed the file name.

Could get individual files, but I would now need to write a Java program or script to put it together.

**Comment by derekcicerone** [comment]
Hmm weird, I'm not entirely sure then. It should work with single file output and module type set to none.

**Comment by derekcicerone** [comment]
If there is a GitHub project I could look at, I might be able to load it and figure out what is going on.

**Comment by Palmer-JC** [comment]
It is BabylonJS/Extensions, but the split out has not been done at github, yet.  Also, the non-repository version is not working now.  I did update plugin today from about a week ago.

Could .zip on Google drive tomorrow the non-repository version.  It now works exactly the same.

**Comment by derekcicerone** [comment]
Cool, yeah, would love to check it out. It could very well be a plugin bug since we don't often build to single file outputs. You'll also want to make sure you have the latest plugin version since there have been some fixes recently that could impact the built files.

**Comment by Palmer-JC** [comment]
Ok.  Will notify with link.  AM Eastern time.

**Comment by Palmer-JC** [comment]
Here is a link:  (Google drive inspects a zip, not provide download)
https://www.dropbox.com/s/6bkc2dq9xba1t8e/proj.zip?dl=0

What about node dependency versions?

**Comment by Palmer-JC** [comment]
Just got notice that there is a Java 8 update, does this matter as well?  My plugin is 1.5.0v20150129-2148

**Comment by derekcicerone** [comment]
I don't see any Eclipse settings in the zip file. What is the project structure supposed to look like?

I'd suggest the latest Nodejs (whatever that is). If you are seeing auto-completion or syntax highlighting, you should be good though.

Java 8 isn't related.

Consider downgrading to the 1.4 plugin - 1.5 is unstable. Downgrading requires uninstalling the plugin, rebooting, then reinstalling from the official release site (vs the develop site).

**Comment by Palmer-JC** [comment]
Went back to production, 1.4.  Was pointing to test at your request a while back for something else.  Building slow first time, like doing something, but still nothing.  Switched to directory output, and get individuals.

I made project as File > New > Project ...  , then selected General Project.  typed "non-repository" for project name.  Copied the Source & References dir from repository.  There is a .project file in zip. 

Am getting auto-completion menus with cntrl-space.

**Comment by derekcicerone** [comment]
Ok, can you remind me of the thing you'd like this to do which isn't working? single file output?

**Comment by derekcicerone** [comment]
Single file output is working for me with these settings:
![screen shot 2015-02-04 at 12 52 00 pm](https://cloud.githubusercontent.com/assets/1081904/6046046/a985ce6c-ac6c-11e4-9671-45e269584ba7.png)

**Comment by Palmer-JC** [comment]
In my system the Generate corresponding .d.ts files is also checked,  see in def file:
compiler.generateDeclarationFiles=true

The project will not build a single file, only a directory of single files.

**Comment by derekcicerone** [comment]
Weird - I just checked that off here and its working fine. Can you check out the error view to see if there are some exceptions?

**Comment by Palmer-JC** [comment]
There were errors in the BabylonJS repository in a different project.  It is built with gulp, and seems to do less checking.

Closed everything but this, restarted.  Nothing.  Going to take this over to my Mac, on Ubuntu now.

**Comment by Palmer-JC** [comment]
using the same dropbox you used.  I built completely new workspace & project and in worked on Mac.

Plugin is older there: 1.0.1.v20140918, but Eclipse is 4.4.1, while Ubuntu is 4.4.0.  Checking for updates does show the newer version, but will not allow to check, says insufficient privileges.  To the shell!

**Comment by Palmer-JC** [comment]
Uncle.  Yesterday, I rebuilt my Eclipse system on Ubuntu.  Tried a whole bunch of stuff & no success.  The fact that you got it to work on Windows, and I got to work on Mac is not encouraging.  I even tried the other Eclipse Typescript plug-in.  Massive errors, but have to admit I was drooling at the code collapsing features.

Got up and just built an Ant script to do the combine, & added it onto the end of the build.  Got extra "__extends" stuff, but it runs. (can manually delete for my infrequent commits).

<?xml version="1.0" encoding="UTF-8"?>
<project name="combine" default="full">
    <description>
        combine separate .js and .d.ts files
    </description>
	
    <target name="combine">
    	
    	<concat destfile="morph.1.2.-debug.js" fixlastline="true">
        	<filelist dir="out"
        	    files="ReferenceDeformation.js, EventSeries.js, Mesh.js, ShapeKeyGroup.js, MakeHuman/Sentence.js, AudioRecorder.js"/>         
    	</concat>
    		
    	<concat destfile="morph.1.2.d.ts" fixlastline="true">
        	<filelist dir="out"
        	    files="ReferenceDeformation.d.ts, EventSeries.d.ts, Mesh.d.ts, ShapeKeyGroup.d.ts, MakeHuman/Sentence.d.ts, AudioRecorder.d.ts"/>         
    	</concat>
    		
    </target>
    
    <target name="copy_js">
        <copy file="morph.1.2.-debug.js" tofile="Blender/blender-test/lib/morph.js"/>
    </target>
    
    <target name="full" depends="combine,copy_js"></target>

</project>
