### ISSUE TITLE
Question : Does plugin support cross-project compilation for external module ?

### ISSUE THREAD

**Issue by KouheiToki** [palantir/eclipse-typescript#229]
I am very impressed your plugin. 
Currentry I am using in my project.

And I have a problem.

I use TypeScript's external module compiled for AMD.
And I do cross-project compilation, say A project references B project.
But A project cannot reference B project, compile error don't disappear at A project.
(When internal module, I can successfully do cross-project compilation.)

Could you tell me if plugin support cross-project compilation for external module ?

Thanks in advance.

**Comment by derekcicerone** [comment]
Good question - external modules which use relative paths are currently unsupported across projects. We actually switched off of external modules for our projects in part due to the pain of getting it working across projects. You could try named modules (which were recently added to TypeScript).

**Comment by KouheiToki** [comment]
Thank you ! I will try.
