### ISSUE TITLE
Question: Is there a good way to output one file with correct order of classes when using cross-project compilation ?

### ISSUE THREAD

**Issue by KouheiToki** [palantir/eclipse-typescript#230]
I am using cross-project compilation output to one file with internal module.

I want output file written correct order of classes(dependended class first), so I am using "/// <reference...".
When reference other projet's ts file by "/// <reference...", I let path include other project's folder like "../../otherproject/ts-output/foo.ts"(long, tedious, depend on project name...). 

Coud you tell me better way if exists ?
Thanks in advance.

**Comment by derekcicerone** [comment]
The way we use cross-project compilation is that we generate one output (file or directory of files) per project (versus one across projects). Perhaps if you want a single output file it would make more sense to just put everything in a single project as well?

**Comment by KouheiToki** [comment]
Thank you for reply.

I have three eclipse projects. One for utility (say util project), other two are web application respectively(say app1 and app2 project).
App1 and app2 depends util project, and deploy to different ap server. So I want one output across projects for app1 and app2 respectively.

By the way, my problem is caused by module aliasing using import sentence(import sentence called at load time, so correct order of classes is necessary). When I remove import sentence(directly specifiy module name in functions), my problem is gone(no need correct order of classes).

**Comment by derekcicerone** [comment]
The way we've been handling a design like this is to compile per-project JavaScript and definition files and then have our web app load all the necessary JavaScript files (and have the downstream projects reference the definition files using the cross-project support).

**Comment by KouheiToki** [comment]
I see... but, I think compile per-project cannot output two project's JavaScript in one webapp folder. So need to copy JavaScript manually when depended project updated. Is this correct ?

**Comment by derekcicerone** [comment]
That's correct - each project can only build to a location within the project. We solve this by symlinking the built files into the web server.

**Comment by KouheiToki** [comment]
That's nice. Because when I update depended project, depending project don't regenerate JavaScript. But your solution using symlinking, updating depended project reflect immediately(more productive).

**Comment by derekcicerone** [comment]
Exactly :)
