### ISSUE TITLE
Cannot find name 'MyClass'.

### ISSUE THREAD

**Issue by legoheld** [palantir/eclipse-typescript#233]
I have a Problem with my own Classes that are not found with the Plugin.
For example I have two Classes in two Files:

**Speaker.ts**
```typescript
module demo {
	
	export class Speaker {
		
		public say():string {
			return "hello";
		}
	}
}
```

**Room.ts**
```typescript
/// <references path="Speaker.ts" />

module demo {
	export class Room {
		
		constructor() {
			var person1 = new Speaker();
		}
	}
}
```

The error I get is that my Speaker Class if not found in my Room constructor.
So I tried:
* with an absolute reference path
* with or without module name (demo)
* without the reference path ( As far as I understood, its not really required because it scans the full eclipse project for .ts files)

Maybe its just a setup issue.
I couldn't find any demo projects to see how others use the plugin.

**Comment by derekcicerone** [comment]
That looks like it should work. Have you enabled the TypeScript builder support for that project?

**Comment by legoheld** [comment]
Thats what I though too - It should work.
Ok, I tried again with the TypescriptBuilder and indeed seems to work.
I usually build my typescript source with gulp so I though I dont need the builder.

**Comment by derekcicerone** [comment]
Cool, yeah, the name is misleading. It's necessary for anything more than syntax highlighting. Even with the builder on, it doesn't mean it has to actually build files though. It just provides the support necessary.

**Comment by legoheld** [comment]
Thanks a lot. Yes, its a bit misleading. Would be cool to have an example project to see how its working.
One more issue I have is with declaration files.
The plugin should also index .d.ts files, no? So do I need a special import or reference path?
It doesn't recognise the classes from the declaration file.

**Comment by derekcicerone** [comment]
Declaration files should just work so long as they are in a source folder (or no source folders are configured).
