### ISSUE TITLE
TypeScript plugin not generating the JS output file

### ISSUE THREAD

**Issue by kruegeGH** [palantir/eclipse-typescript#234]
I have version 1.4.0.v20150129-2147 of the TypeScript plugin and am using STS version 3.6.3.  I have noticed the plugin seems to have issues building the JS output file for all my TS files.  I have gotten it to work with a small set of TS files (so I know it works sometimes) but when I have all my TS files in my project it doesn't build the JS file at all.  Quite honestly it doesn't even look like it runs during that scenario.  What is puzzling for me is that I had setup an external builder in STS to run the tsc command to generate the JS file and that works just fine.  I can also properly generate a JS file by directly executing the tsc command from the command prompt.  The fact that I can successfully generate the JS file using two other means is leading me to believe that there is something going on with the plugin.  I've had coworker test it out for me as well and he gets the exact same results.

Has anyone encountered a similar issue or know of some kind of logging that can be turned on for the TypeScript plugin?  I would prefer to just use the plugin itself for all of my compilation/transpiling needs but if the external builder I setup is the only convenient way I can get a successful JS file to be written then I will continue to use that and just wait and see if future versions of the plugin manage to fix the issue.

**Comment by derekcicerone** [comment]
Hmm, that sounds bad - do you see any errors in the error log? Have you configured the project builder for TypeScript? Can you share the project configuration settings?

**Comment by kruegeGH** [comment]
Thanks for the reply Derek.  No, unfortunately I don't see any errors in the log which is why I was wondering if there was some kind of option to turn logging on for it. 

In regards to your second question are you talking about the Configure -> Enable TypeScript Builder option that you can get to by right clicking on the project?  If so then yes I have that configured.

I also wasn't 100% sure which project configuration settings you wanted but if you were referring to the settings for the com.palantir.typescript.prefs file they are as follows:

build.path.exportedFolder=
build.path.sourceFolder=WebContent/static/typescript/myApp
compiler.codeGenTarget=ECMASCRIPT5
compiler.compileOnSave=true
compiler.generateDeclarationFiles=false
compiler.mapSourceFiles=true
compiler.moduleGenTarget=UNSPECIFIED
compiler.noImplicitAny=true
compiler.noLib=false
compiler.outputDirOption=WebContent/static/typescript/js
compiler.outputFileOption=Trips.js
compiler.removeComments=true
eclipse.preferences.version=1

Also, I don't know if it helps any for comparison purposes but when I run it from the command line (which works for me) this is all I put on the command line:

tsc @ts-files.txt --target ES5 --sourceMap --removeComments --out ..\js\App.js

The ts-files.txt just contains the list of all the TS files that are used for my project.

Oh, and just a heads up, I am at the end of my work day so will not have a chance to check back on this until tomorrow.

**Comment by derekcicerone** [comment]
Thanks for the details. Looking at your settings, it looks like files will only be compiled if they are contained within "WebContent/static/typescript/myApp" (only files in this directory will be compiled) and then they will be output as a single file "Trips.js" to "WebContent/static/typescript/js". Is that what you expect? (it seems to differ from the command line for example)

To be honest, the single-file output mode isn't very well tested so its very possible that is the issue. Maybe try the multiple file output and see if that helps?

**Comment by kruegeGH** [comment]
Derek, yeah sorry about that.  The command line version I gave you should have ended with Trips.js not App.js.  It is doing the same thing that we're trying to get the plugin to do and that is (as you noted) compile all the TS files in the myApp folder and any subdirectory into one concatenated JS file.  Like I had mentioned earlier I have gotten the plugin to work before but it seems to be very picky about when it does.  For example, I have 7 subdirectories within the myApp folder and have noticed that if I randomly remove some folders it will build the concatenated JS file properly but if I keep all the subdirectories in then it won't build the JS file.

I have also noticed that it's not really specific to any kind of folder structure as I had tested it by using just one folder and putting all my TS files from the other subdirectories into that one folder and then compiling that one folder.  I ran into the same problem doing that (and also the same random quirk where if I remove some random files it will generate the concatenated JS file otherwise it won't generate the JS file).  For my single folder test I was also still able to generate what I wanted straight from the command line or using the external builder I had setup.  It just seems to be the plugin.

The multiple file option that you suggested has not been an issue for me and has always worked.  It just seems to be something quirky with compiling into one concatenated JS file.  For the project that I'm working at we have decided to use the one concatenated file approach which is the only reason why we're looking for a way to do that successfully within the plugin.

**Comment by derekcicerone** [comment]
Ah ok, so it most likely all ties back to the single file output it seems. If you can come up with a small repro I could try out and debug I could look into this more but I'm afraid at present there likely isn't much further I can do since we don't use the single file output. I have no trouble believing it could be somewhat flaky given that it is somewhat untested.

**Comment by kruegeGH** [comment]
Ok, I created a repo of what isn't working for me.  I hope that right since I've never used/created a git repo before.

The files that are up there are actually supposed to reside in a parent folder called TestProject2 which is the name of my workspace in STS (I mention this because I believe I screwed that part up trying to upload my files to github).  If you need me to redo it just let me know and I'll give it another shot.

**Comment by derekcicerone** [comment]
Cool, thanks - I'm going to take a look this weekend.

**Comment by kruegeGH** [comment]
Thanks Derek.  If you find that it just "works" for you don't be too surprised.  I used those same files to create multiple copies of that project to narrow down the problem and noticed that sometimes the concatenated JS file just plain worked despite me making no changes whatsoever whereas other times it wouldn't.  The copy I uploaded is the one test project that I've been consistently able to get to not work correctly (at least for my machine and one of my coworkers machines).

Out of curiosity since you mentioned you guys don't use the single file output what do you use as far as concatenation goes for a single JS file?  Or do you only deal with many smaller individual JS files?  And would you happen to know if the feature to concatenate all the individual JS files into a single JS file is going to become "official" (and by default fully tested)?  If it's going to be a feature that won't be fully tested for a while maybe it would make sense to temporarily remove it until it has been fully tested.  If nothing else it would prevent people like me from bugging you.  :)

**Comment by derekcicerone** [comment]
Thanks for the great repro - I think I was able to figure out what was going on and fix the issue. The update with a fix should be out shortly (within 15 mins). Please let me know if it works.

**Comment by kruegeGH** [comment]
Hey thanks a lot Derek!  I'll check it out when I'm back in the office on Monday and let you know.  Now stop working and enjoy your weekend.  :)

**Comment by derekcicerone** [comment]
:)

**Comment by kruegeGH** [comment]
Hi Derek.  I just downloaded your update and checked it out here at the office.  It's working great!  Thanks a lot!  I really appreciate all the work you put into fixing that issue for me.

**Comment by derekcicerone** [comment]
Awesome, glad to hear it worked out! Sorry for the inconvenience of having to deal with that in the first place.
