### ISSUE TITLE
UnitTest Support

### ISSUE THREAD

**Issue by pofuk** [palantir/eclipse-typescript#236]
I would be really great if you add UnitTesting support (Code coverage as well but not necessary). Any serious project will use this feature. Visual Studio supports this very well.

**Comment by derekcicerone** [comment]
Hmm, can you explain a bit more what this would mean? I'm not sure if this is a request for TypeScript specifically or for Eclipse to have a plug-in for this more generally.

**Comment by pofuk** [comment]
What I would like to have is ability to run tests using eclipse like jUnit is used.
 i.e Right click on SomeTest.ts fila, Run As -> TsUnit Test. To see wich method is failing and not. 
And also to be able to see coverage like EclEmma does in eclipse. 

I thing VS does this by Compilint to js (this plugin does that already), than runs th code on node.js and than reports back to IDE using source maps.

**Comment by derekcicerone** [comment]
Neat :) Sounds like a cool Eclipse plug-in which would be useful for more than just TypeScript. I think it would be out of scope for this plug-in since it doesn't relate specifically to TypeScript.
