### ISSUE TITLE
Eclipse unable to find d.ts files

### ISSUE THREAD

**Issue by a3chic9** [palantir/eclipse-typescript#239]
I have my project set up where my TypeScript files are in a src/ directory which also contains a typings/ directory for all of my d.ts files. However, despite having the jQuery type definition installed in that location, I am still getting a "File not found" error. I'm getting a similar error for a selenium-webdriver file as well. Because these are not being recognized I'm now getting over 100 errors.

Description | Resource | Path | Location | Type
---------------|--------------|-------|------------|-------
File 'eclipse:/typescript-angular/src/typings/jquery/jquery.d.ts' not found. | angular.d.ts | /typescript-angular/src/typings/angularjs | line 8 | TypeScript Problem
File 'eclipse:/typescript-angular/src/typings/selenium-webdriver/selenium-webdriver.d.ts' not found. | angular-protractor.d.ts | /typescript-angular/src/typings/angular-protractor | line 7 | TypeScript Problem

**Comment by derekcicerone** [comment]
Hmm, that's weird. Nothing has changed recently to make this happen. Was it working previously?

**Comment by a3chic9** [comment]
No. Honestly it could be my fault for not setting things up right but I'm surprised that those definitions aren't being recognized when other ones in the typings directory are. Plus these are all downloaded using the tsd cli tool.

I couldn't fine any documentation on how to set the TypeScript property for the project so I set it up as

**Source folder(s):** src
**Exported folder(s):** _[none]_
**Output folder:** app
**Output file name:** _[none]_

**Comment by derekcicerone** [comment]
TSD likes to set things up in directories like:
/typings
  /angular
    /angular.js

Do you have that directory structure? We use TSD as well and it works well.

**Comment by a3chic9** [comment]
Yeah. The directories for angular and jquery are
* /src/typings/angularjs/angular.d.ts
* /src/typings/jquery/jquery.d.ts

**Comment by a3chic9** [comment]
I've removed the directory containing the definition for angular-scenario and that cleaned things up a lot. Maybe it was a problem with a name conflict in the definition file.
