### ISSUE TITLE
Refactor /// <reference path="..." /> references on rename/move

### ISSUE THREAD

**Issue by a3chic9** [palantir/eclipse-typescript#240]
Because the reference paths are in comments, Eclipse doesn't look at them when re-factoring file names. This could be very tedious to do manually. There are two changes I can think of that could cause reference errors. It would be nice to have these changes

1. Renaming a file
   * Affects files referencing the renamed file
2. Moving a file
  * Affects files referencing the moved file
  * Affects relative file references within the moved file

**Comment by derekcicerone** [comment]
This is good feedback - unfortunately it wouldn't be implemented in the eclipse plug-in though - it needs to occur upstream in the TypeScript language services. You can file an issue on their project here:
https://github.com/Microsoft/TypeScript
