### ISSUE TITLE
ES6 default library always included

### ISSUE THREAD

**Issue by mttcr** [palantir/eclipse-typescript#241]
Hello,
When using the develop branch, ecma6 features in lib.es6.d.ts are used for autocomplete and build. 
When targetting to ecma5, shouldn't the definition file not be included thus display some build errors ?
For example, String.startsWith is in lib.es6.d.ts, it compiles fine, but I targetted my workspace to ES5

**Comment by derekcicerone** [comment]
Hmm, that's weird. Wanna contribute a fix for this?

**Comment by mttcr** [comment]
Maybe this patch could fix the issue, what do you think ?
```
diff --git a/com.palantir.typescript/bridge/src/languageServiceHost.ts b/com.palantir.typescript/bridge/src/languageServiceHost.ts
index 8f5a71f..3bcb0e0 100644
--- a/com.palantir.typescript/bridge/src/languageServiceHost.ts
+++ b/com.palantir.typescript/bridge/src/languageServiceHost.ts
@@ -59,9 +59,12 @@
         public getScriptFileNames() {
             return Object.getOwnPropertyNames(this.fileInfos).filter((fileName) => {
                 // include the default library definition file if its enabled
-                if (fileName === LIB_FILE_NAME || fileName === LIB_ES6_FILE_NAME) {
+                if (fileName === LIB_FILE_NAME) {
                     return !this.compilationSettings.noLib;
                 }
+                else if(fileName === LIB_ES6_FILE_NAME) {
+                    return !this.compilationSettings.noLib && this.compilationSettings.target === ts.ScriptTarget.ES6  ;
+                }
 
                 return this.fileFilter(fileName);
             });
```

**Comment by derekcicerone** [comment]
Oh, sorry, looking at this more closely, are you pulling in lib.es6.d.ts? If so, I think you'll probably not want to pull that file in if you are targeting ES5.

The compiler shouldn't be including the ES6 library file if you are targeting ES5. Are you seeing different behavior?

**Comment by mttcr** [comment]
Well I never reference the lib.es6.d.ts file in my sources, I assumed it was added automatically by the plugin.

**Comment by derekcicerone** [comment]
Hmm yeah, I'm still not sure how this might be happening. Its possible I fixed it in the develop release. Might be a good idea to wait for that before trying to diagnose this further. It should be releasing very soon.

**Comment by mttcr** [comment]
Still the same error
![image](https://cloud.githubusercontent.com/assets/8974534/8132394/cbfc6bda-1121-11e5-8ae7-d6ff0440aa50.png)
While targetting to ES5
![image](https://cloud.githubusercontent.com/assets/8974534/8132413/eb8be7e6-1121-11e5-9728-8aea67ea8b84.png)
and no specific es6 lib in source folder
![image](https://cloud.githubusercontent.com/assets/8974534/8132423/fc9c5228-1121-11e5-9d2a-453c75306efd.png)
With the current version 1.5.0.v20150607-2235

**Comment by derekcicerone** [comment]
Thanks for the details, I'm gonna look into this early next week.
