### ISSUE TITLE
Hidden errors on develop branch

### ISSUE THREAD

**Issue by mttcr** [palantir/eclipse-typescript#242]
Hello,
When compiling, errors are hidden on a specific case : 
* Using the develop version of the plugin
* Have related projects in workspaces
* error occurring  in the referenced project

For example:
* Create a sample project test1 with the following structure
```
/src
|--/test
|--/test2
|  |--Test2.ts
/build
```
For this project, typescript configuration is : 
Source folder: src
Exported folders : src/test;src/test2
Output folder: build
![projects](https://cloud.githubusercontent.com/assets/8974534/7024859/02e203f0-dd40-11e4-9e21-dbb90ea8b96d.png)

* Create another sample project test2 with the following structure
```
/src
|--/test2
|  |--Test.ts
/build
```

The configuration for this project is : 
Source folder : src
Output folder : build

![projects](https://cloud.githubusercontent.com/assets/8974534/7024877/1a7721da-dd40-11e4-9a6e-98d41e0c4ae9.png)

The project test2 references the project test1 in "Project References"
![projects](https://cloud.githubusercontent.com/assets/8974534/7024900/3259beac-dd40-11e4-8160-b9b146ff81ea.png)

![projects](https://cloud.githubusercontent.com/assets/8974534/7024843/e306bfda-dd3f-11e4-8501-b3bf211da318.png)

* In the file Test2, lets write an error : 
```
module test2
{
    export class Test2
    {
        private data: toto;
    }
}
```
The type `toto` does not exist.
I have build auto enabled on the workspace
When doing Project > clean > clean all project, the error is shown.
![error](https://cloud.githubusercontent.com/assets/8974534/7024913/45a44810-dd40-11e4-8351-9630d317dfc6.png)

But when editing the file (adding a space for example) and saving, the error disappears.
![error](https://cloud.githubusercontent.com/assets/8974534/7024923/58ca6b40-dd40-11e4-806b-944256d9c19b.png)

I hope it's clear enough to find the reason why it does that.
It does not happen without related projects and multiple exported folders

**Comment by derekcicerone** [comment]
Hmm, weird, thanks for reporting. Please let me know if you would be interested in contributing a fix for this one.

**Comment by mttcr** [comment]
To be honest, I think I won't be able to find such time at work unfortunately

**Comment by mttcr** [comment]
A little up on this one, the problem is still present, and now on master.
I updated the plugin with the standard update site, and the error occurs.
To simplify the problem, no error is shown in a file of an exported folder of a referenced project with or without "build automatically"

**Comment by mttcr** [comment]
Same as #267 which is corrected.

**Comment by derekcicerone** [comment]
Oh right. I need to merge master into develop. Lemme try to get that shortly.

**Comment by derekcicerone** [comment]
Just pushed the merge - please try updating to the latest develop in ~20 mins.
