### ISSUE TITLE
Outdated lib.d.ts on version 1.4.0.v20150315-1844

### ISSUE THREAD

**Issue by diogosantana** [palantir/eclipse-typescript#243]
The lib.d.ts file located at com/palantir/typescript/serices/language is outdated.

I noted that because FormData declaration did not have the constructor optional parameter.

The last lib.d.ts:

    new (form?: HTMLFormElement): FormData;

The plugin lib.d.ts:

    new(): FormData;

**Comment by diogosantana** [comment]
It is actually a Typescript error as we can see in https://github.com/Microsoft/TypeScript/issues/1074.

**Comment by derekcicerone** [comment]
As a workaround for now you can supply your own lib.d.ts file.
