### ISSUE TITLE
Warning on missing type annotation

### ISSUE THREAD

**Issue by JirkaDellOro** [palantir/eclipse-typescript#249]
I started using TypeScript as the first language for teaching programming at our university. Though it's sometimes recommended to leave typing to TypeScript, I force my students to explicitly type in order to create the proper mental modell and simply for practice purpose.

It would be very helpful to have an option to display warnings at declarations with implicit types. So far, Eclipse only warns on implicit any-types.

Hard to implement?

**Comment by derekcicerone** [comment]
The plug-in actually gets all its functionality like this from the underlying TypeScript language services. Feature requests for additional warnings would need to go to the TypeScript team and then we could hook them up in the plug-in.

**Comment by JirkaDellOro** [comment]
Hello Derek,

 

the TypeScript-Team discussed it and this is the result:

It should be much simpler to add a new rule to tslint. It Should also work with the eclipse plugin, they are both developed by  <https://github.com/Palantir> @Palantir :)

What do you think?

 

 

 

Von: Derek Cicerone [mailto:notifications@github.com] 
Gesendet: Donnerstag, 14. Mai 2015 18:14
An: palantir/eclipse-typescript
Cc: JirkaDellOro
Betreff: Re: [eclipse-typescript] Warning on missing type annotation (#249)

 

The plug-in actually gets all its functionality like this from the underlying TypeScript language services. Feature requests for additional warnings would need to go to the TypeScript team and then we could hook them up in the plug-in.

**Comment by derekcicerone** [comment]
Makes total sense. Wanna file an issue in tslint?

**Comment by ashwinr** [comment]
@JirkaDellOro do you have a link to the typescript discussion?

**Comment by JirkaDellOro** [comment]
Yes, here it is:
https://github.com/Microsoft/TypeScript/issues/3177#issuecomment-102315191

**Comment by JirkaDellOro** [comment]
I've taken a look in the tslint-Readme. It says there:

- typedef enforces type definitions to exist. Rule options:
    "call-signature" checks return type of functions
    "parameter" checks type specifier of function parameters
    "property-declaration" checks return types of interface properties
    "variable-declaration" checks variable declarations
    "member-variable-declaration" checks member variable declarations

So it looks like what I need already exists, besides other useful checks in the linter. If so, I'd need a way to adjust those options and make the results visible in Eclipse.

**Comment by JirkaDellOro** [comment]
Or better of course, to get the TypeScript-Plugin to do these checks...

**Comment by derekcicerone** [comment]
There is a separate eclipse-tslint plugin for tslint stuff - this plugin only covers core TypeScript functionality.

**Comment by JirkaDellOro** [comment]
Sorry, I can't safely interpret the last comment. Who is the tslint folks and do they work on both linters, tslint and the eclipse-tslint plugin?

**Comment by derekcicerone** [comment]
Ah yeah sorry, there are 2 projects separate from this one:
* https://github.com/palantir/tslint
* https://github.com/palantir/eclipse-tslint

The linter is tslint - eclipse-tslint is just an eclipse plugin which uses tslint. So if you want a tslint change, you'll want to file an issue on the tslint project. If the issue is related to the Eclipse integration specifically then eclipse-tslint is more appropriate.

**Comment by JirkaDellOro** [comment]
Thanks a lot for the advices, eclipse-tslint pretty much does everything I wish! Now I'll be reporting issues there.
