### ISSUE TITLE
support TypeScript version 1.5

### ISSUE THREAD

**Issue by atsu85** [palantir/eclipse-typescript#252]
Hello,
Please add the support for version 1.5 as beta version of TypeScript 1.5 is out, as announced here:
http://blogs.msdn.com/b/typescript/archive/2015/04/30/announcing-typescript-1-5-beta.aspx

TS1.5 support is almost a "must have" for Aurelia + TypeScript setup. Looks like VisualStudio, WebStorm, Atom and Sublime already support TS1.5-beta...

**Comment by ashwinr** [comment]
please use the develop version of the plugin which supports 1.5: https://github.com/palantir/eclipse-typescript/wiki#develop-update-site
