### ISSUE TITLE
compiler error in angular 2 sample

### ISSUE THREAD

**Issue by jjfraney** [palantir/eclipse-typescript#254]
I followed this tutorial (https://angular.io/docs/js/latest/quickstart.html) for angular 2 using vi.  Then, I did the same with an eclipse project and palantir.  The palantir plugin finds errors that tsc does not.  How can I resolve these?  How can I set 'emitDecoratorMetadata' in the palantir Typescript builder? (maybe it matters-I don't know).

![image](https://cloud.githubusercontent.com/assets/95555/7902950/301c00da-079a-11e5-950d-6163fbbb595a.png)

**Comment by derekcicerone** [comment]
I think some of those features (like decorators) require using the as-yet unreleased version of TypeScript plug-in (1.5). You can get it by switching to the develop update site. Instructions for doing so are in the wiki.

**Comment by Waog** [comment]
using 1.5 from the dev branch worked for me!

**Comment by derekcicerone** [comment]
I just merged the 1.5 support (which includes decorator support) into the main (non-develop) release so you should be able to switch back to normal releases now.
