### ISSUE TITLE
Generic way to add parameters

### ISSUE THREAD

**Issue by Waog** [palantir/eclipse-typescript#261]
Feature Request: I'd like to have a way, to specify arbitrary parameters in the properties as plain text.

Background
--
Newer Versions of the TS compiler may have parameters which are not yet implemented as check boxes for the properties menu. A generic text field for additional parameters would help here to overcome the gap between *tsc* and your *eclipse plugin*. E.g. In my current case `--experimentalDecorators` is missing.

**Comment by derekcicerone** [comment]
experimentalDecorators is implemented in the latest release. please update.

**Comment by derekcicerone** [comment]
![screen shot 2015-06-23 at 10 25 36 am](https://cloud.githubusercontent.com/assets/1081904/8312575/3634251a-1992-11e5-933e-9e155485e6a9.png)

**Comment by derekcicerone** [comment]
Thinking about this request more I think I'd like to just implement first class support for whichever properties are required. Some of them require special handling in the plugin.
