### ISSUE TITLE
--experimentalDecorators not recognized

### ISSUE THREAD

**Issue by Waog** [palantir/eclipse-typescript#262]
I still get the following error:
*Experimental support for decorators is a feature that is subject to change in a future release. Specify '--experimentalDecorators' to remove this warning.*

I enabled the checkbox *Enable experimental support for ES7 decorators* and an according entry is present in the preferences file: `compiler.experimentalDecorators=true`. 

Installed plugin info:
`  TypeScript	1.5.0.v20150620-1653	com.palantir.typescript.feature.feature.group	Palantir Technologies, Inc.`

**Comment by Waog** [comment]
Applying the following changes fixed the problem for some reason. Don't exactly know why:
![image](https://cloud.githubusercontent.com/assets/5098472/8313319/47db9a3c-19e2-11e5-9427-c2a44974f64d.png)

**Comment by Waog** [comment]
May have been caused by delayed updates of eclipse, since not much time has passed between recognizing these errors and changing the config file.

**Comment by derekcicerone** [comment]
Weird, it looks properly hooked up to me. Gonna close this for now. Please lemme know if you hit any additional issues.

**Comment by Waog** [comment]
Occasionally this error still pops up in the editor and is removed automatically shortly after (around 5 seconds). The tree in the package explorer gets no error decorators anyway.

**Comment by derekcicerone** [comment]
I wonder if the setting only propagated to some of the language services. Can you try rebooting Eclipse and see if it still occurs?
