### ISSUE TITLE
TypeScript 1.5.0 beta

### ISSUE THREAD

**Issue by paztis** [palantir/eclipse-typescript#266]
Current plugin version works great with TypeScript 1.5.0 alpha, but is not coherent with 1.5.0 beta.
Some breaking change have done in lib.dom.d.ts from alpha to beta, and eclipse plugin don't display errors from 1.5.0 beta tsc compiler.
Is it possible to update to 1.5.0 beta ?
Thanks

**Comment by derekcicerone** [comment]
I think this has been fixed :)
