### ISSUE TITLE
Problem markers no longer showing since update to 1.5

### ISSUE THREAD

**Issue by nealeu** [palantir/eclipse-typescript#267]
Hi,

I've recently updated the plugin from 1.4 to 1.5 and now no longer get any problem markers shown in the problems view.  I only get anything shown if I happen to open the appropriate file.

I used to not have Eclipse generate my .js, but used tsc externally, and Eclipse would still compile the files on change (which it is clearly doing when in an editor).

I've also now enabled "Build all on save" in the project settings for Typescript and nothing is happening

**Comment by derekcicerone** [comment]
Hi Neale, sorry to hear this is breaking. We've been using the latest released plugin for a bit now with no issues in Eclipse Luna. Which version of Eclipse are you using? We haven't tested Mars yet for example. Do you have "build automatically" enabled?

**Comment by nealeu** [comment]
Hi Derek,
I'm on Luna.  I've got Mars downloaded, so may as well give that a go with a fresh workspace.  I wonder if there's just some quirk in config that is preventing this happening.
I'll let you know how I get on.

**Comment by derekcicerone** [comment]
Cool. You might also want to double check the automatic builds are enabled - it's an eclipse-wide setting.

**Comment by nealeu** [comment]
That's no problem... our project includes a lot of Java and is run from within Eclipse, so soon notice if I've got that switched off :)

**Comment by derekcicerone** [comment]
Ah cool :)

**Comment by StefanBrands** [comment]
Hi, Any news on this ? We are also experiencing this problem. We are using Luna.

**Comment by mttcr** [comment]
Hi,
@nealeu, do you use multiple projects referenced with each other ? I've got the same problem in #242

**Comment by StefanBrands** [comment]
We are not using  project references, we are using it in a maven project, with only maven references.

**Comment by nealeu** [comment]
Same for me. Only maven, but all TS is in one module

**Comment by derekcicerone** [comment]
Any errors visible in the Error Log view? I'm still not able to repro this issue.

**Comment by StefanBrands** [comment]
Where do I find that log file ?

**Comment by derekcicerone** [comment]
Its a view in Eclipse, you can find it in Window -> Show View...

**Comment by StefanBrands** [comment]
nothing in there...sorry.

**Comment by derekcicerone** [comment]
Doh, hmm, I'm really not sure what might be happening in that case.

**Comment by StefanBrands** [comment]
Is there a way for me to debug it ?

**Comment by derekcicerone** [comment]
There is but its pretty involved. It requires setting up the dev environment and running the other workspace, then going into the code to see why problem markers aren't being created.

**Comment by StefanBrands** [comment]
How complex is setting up the dev environment ?

**Comment by derekcicerone** [comment]
Its not too bad. The bigger problem is that I won't be able to support you - my time is very limited and cut into small slices of time. So you'd have to figure it out on your own and I could answer questions with long delays most likely (my day starts soon and then I'm not free again for 8 hours).

**Comment by StefanBrands** [comment]
I understand. I'm willing to try this. If you can tel me how to setup the dev env, then I'll figure out the rest... I also have limited time, but I really would like this plugin to work for us, it's the only option we have today.

**Comment by derekcicerone** [comment]
Sorry, thats the part I can't help with. In general, close the repo and run "grunt" to build the TS code. Then you will need to setup a debug profile to launch your workspace. Its kinda tricky :/

**Comment by StefanBrands** [comment]
ok, no problem, maybe I can find out myself. Thank you !

**Comment by StefanBrands** [comment]
I've been debugging this problem. The problem is in TypeScriptBuilder.java, in method incrementalBuild :

These lines of code :
  // re-create the markers for projects which reference this one
        for (IProject referencingProject : this.getProject().getReferencingProjects()) {
            if (!this.languageEndpoint.isProjectInitialized(referencingProject)) {
                this.languageEndpoint.initializeProject(referencingProject);
            }

            this.deleteAllMarkers();
            this.createMarkers(referencingProject, monitor);
        }

the line this.deleteAllMarkers(); , deletes all markers from the current project, not from the referencing project. It should delete the markers from the referencing project.

I hope this helps.

Regards,

Stefan.

**Comment by nealeu** [comment]
Thanks for the fix @StefanBrands and @derekcicerone
