### ISSUE TITLE
Support for tsconfig.json

### ISSUE THREAD

**Issue by jonnermut** [palantir/eclipse-typescript#268]
I have a long standing issue with output files which I've never really resolved, which is that within the one Eclipse project I have two src folders:
src/main/typescript
src/test/typescript

The files in src/test/typescript obviously heavily reference the files in src/main/typescript.

And I want to output two separate .js files, which contain the compiled output for all files in those folders:
main.js
test.js

(I would actually like to add a 3rd folder and output file as well, but need to support this in eclipse first)

For my automated build, I use gradle to collect the input files and run tsc twice. However I've never been able to configure the Eclipse plugin to do the same output.

In typescript 1.5, the gradle step is simpler if I just put a tsconfig.json file in each folders. Then I can just run tsc without any params, and it picks up all .ts files and dumps a single output file as I want.

However it seems the Eclipse plugin doesn't know about tsconfig.json files yet? If I leave output file blank in the typescript settings, it reverts to a .js file per .ts file. If I set it, it compiles both folders into the one file.

Any pointers on how I could set this up?

**Comment by amergey** [comment]
I would be interested in informations related to tsconfig.json support too

**Comment by derekcicerone** [comment]
Makes a lot of sense but I likely won't be able to get to this anytime soon, sorry.

**Comment by glen-84** [comment]
How do you specify compiler options without tsconfig.json?

**Comment by derekcicerone** [comment]
@glen-84 Many compiler options are exposed in the Eclipse settings for each project.

**Comment by glen-84** [comment]
I didn't see any – I'm assuming that I have to enable the TypeScript builder first, but I'm building with Gulp (using a tsconfig.json file), so I don't want the files to be compiled by this extension.

**Comment by derekcicerone** [comment]
The builder needs to be enabled to get the compiler options. Enabling the building doesn't necessarily enable compilation - you can turn compilation off (its called something like "compile on save"). The builder just turns on things like auto-completion and other services.

**Comment by glen-84** [comment]
Thanks @derekcicerone.

Still a +1 for tsconfig support though, as that is where all my configuration is. =)

**Comment by derekcicerone** [comment]
@glen-84 totally agree that would be ideal!

**Comment by alex-okrushko** [comment]
Considering that the last commit was 4 month ago I assume the support for tsconfig.json won't be happening any time soon? Sigh, I guess Visual Studio Code it is :(

**Comment by bgloeckle** [comment]
I had the same problem with https://github.com/diqube/diqube, where I integrated a TypeScript build step into my Apache Maven build system - and I wanted to use Eclipse as IDE. Though some of the compiler options are exposed by the plugin in the Project Properties, not all of them are - and I needed some that are not exposed (resolving dependencies by node modules). What I did to make the plugin work somehow, is that I effectively run the TypeScript build twice in Eclipse: One time by the plugin which compiles to a folder that nothing else depends on (just for the plugin to show me compile errors and allow me to browse the code using Ctrl+Click etc) - and the other by my Maven build - which then compiles files that other depend on (these files are packaged into my output artifacts). 
Apache Maven probably is not the build system most of the people that want to use TypeScript use, but the general idea could be the same for you guys: Simply use two builds (for example a watching grunt in the background that compiles the files that are loaded by the browser, and a build of the eclipse plugin that produces output files noone depends on, but will allow you to use the plugin nicely).

**Comment by derekcicerone** [comment]
@bgloeckle Please feel free to file tickets for missing compiler options. Many of them can be quickly/easily implemented.

**Comment by codler** [comment]
I wish have same behavior as in Visual Studio, now you can have several tsconfig.json in a project.
https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#improved-support-for-tsconfigjson-in-visual-studio-2015

**Comment by lgrignon** [comment]
Hello, I need it badly as well. Other plugins provide it but they are, IMO, less easy to use than this palantir's plugin.
Would you be open to contributions if I PR it?

**Comment by tomshen** [comment]
Hi @lgrignon! We're definitely open to contributions. Feel free to submit a PR.

**Comment by lgrignon** [comment]
Thanks. I just PRed the basics of handling tsconfig:
https://github.com/palantir/eclipse-typescript/pull/323

This is pretty minimalist, but I plan to add the following feature during the days:
- Either disable preferences coming from tsconfig.json in preferences pages OR write to tsconfig if preferences are modified in GUI
- Reload preferences if tsconfig.json file changed
- Support the files property, which includes glob & input files list

Please tell me if any other idea comes to your mind :)

Thanks!

**Comment by glen-84** [comment]
> Either disable preferences coming from tsconfig.json in preferences pages OR write to tsconfig if preferences are modified in GUI

I don't think that you should write to the tsconfig file.

> Support the files property, which includes glob & input files list

TypeScript 2.0 will support glob-style pattern matching in the `include` and `exclude` properties. (https://github.com/Microsoft/TypeScript/pull/8841)

**Comment by lgrignon** [comment]
Thanks for your feedbacks, the final PR is here #323

**Comment by tomshen** [comment]
Addressed in #323.
