### ISSUE TITLE
How to exclude specific folder from validation?

### ISSUE THREAD

**Issue by fduch-stranger** [palantir/eclipse-typescript#273]
I want to exclude node_modules folder from validation as it has a lot of compilation errors. My project  looks like:
![screenshot001](https://cloud.githubusercontent.com/assets/6566845/9197930/09296212-4041-11e5-9f6d-4fc5e23f145e.png)

But unfortunately I can't find TypeScript validator in the validator's list. This looks like a defect. 
![screenshot002](https://cloud.githubusercontent.com/assets/6566845/9197981/6aa2ff80-4041-11e5-9e03-af4fb5944f85.png)

Eclipse version is 4.5,
Plugin versions:
TypeScript	1.5.0.v20150727-0436	com.palantir.typescript.feature.feature.group	Palantir Technologies, Inc.

**Comment by derekcicerone** [comment]
Eclipse supports a mechanism for excluding entire folders directly.

In addition, the TypeScript plug-in allows folders to be listed on a per-project basis for inclusion so you could just list the folders to include there.

**Comment by reformed** [comment]
@derekcicerone what is this mechanism? How can entire folders be excluded from validation?
