### ISSUE TITLE
TSLint "interface-name" rule not correcly applied

### ISSUE THREAD

**Issue by nlenoire** [palantir/eclipse-typescript#275]
Hello,
I do not want tslint to warn in case interface name does not start with 'I'. Also, I configured tslint.json with the rule:
"interface-name": false,

However, my typescript editor is still displaying a warning decorator saying "Interface name must be capitalized I" (whatever is the value of the interface-name rule, actually).
Note that if I run tslint using the command line, then rule is applied correctly.

**Comment by adidahiya** [comment]
this is the eclipse-tslint project (distinct from eclipse-typescript): https://github.com/palantir/eclipse-tslint

**Comment by derekcicerone** [comment]
Closing since this project is not related to tslint.
