### ISSUE TITLE
Editor displays warning about "mysterious" tslint rules 

### ISSUE THREAD

**Issue by nlenoire** [palantir/eclipse-typescript#276]
I have the following tslint rule: <code>"indent": [true, "tabs"]</code>

When applied inside the editor to the following commented code, it shows multiple warnings:
![ts-editor](https://cloud.githubusercontent.com/assets/14158698/9994194/6c7f0f00-607c-11e5-9a88-0b121a529e9b.png)

Here are details about the raised warnings
* line 10
** space indentation expected
* line 15
** space indentation expected

However,
* No such warning should be raised against commented code
* Those warning are in any case wrong and do not apply actual rules

**Comment by adidahiya** [comment]
this is the eclipse-tslint project; distinct from eclipse-typescript: https://github.com/palantir/eclipse-tslint

**Comment by derekcicerone** [comment]
Closing since this project is not related to tslint.
