### ISSUE TITLE
No support for SuppressExcessPropertyErrors

### ISSUE THREAD

**Issue by BlacKCaT27** [palantir/eclipse-typescript#281]
With TS 1.6, stricter type checking is being done on declared objects [(see here)](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#strict-object-literal-assignment-checking).  This check is a potential breaking change, however these new checks can be suppressed via the tsc argument --suppressExcessPropertyErrors. 

Currently, palantir doesn't support this notion, so there is no way to disable the checks in Eclipse, even though builds using ant or other build tools can pass assuming the argument is given. I can configure Eclipse to use a custom builder instead of Palantir's builder, but that doesn't stop palantir's checks from showing errors (either that, or I've misconfigured my custom builder some how). 

Is there anything that could be done here?

**Comment by derekcicerone** [comment]
Sounds like we need to expose that compiler option in the UI. Wanna take a shot at submitting a PR for it?

**Comment by BlacKCaT27** [comment]
Is that all it would take? I'm not familiar with the palantir codebase, so
I'm not sure what, if any, work would need to be done aside from a UI
option to pass that argument. If it's that simple I'd be happy to take a
look, though I'm not sure when I'd find the time :/

**Comment by derekcicerone** [comment]
Yeah, it should be a pretty simple change. I could also look into this weekend if that's not too late.

**Comment by BlacKCaT27** [comment]
I'll try to take a look, then. If I get hung up or just can't find the time (or the weekend comes), maybe you can just throw something together.

Thanks

**Comment by BlacKCaT27** [comment]
You weren't kidding. That was a pretty simple add-in. Submitted PR #282 for review :)
