### ISSUE TITLE
Compile on save

### ISSUE THREAD

**Issue by PDSBGreg** [palantir/eclipse-typescript#288]
This isn't a bug (I don't think), but I can't find out how to get the TS file to compile to JS on save. The only option I can find in the Eclipse prefs is "Compile all TypeScript files on build". Am I missing something obvious? Simply saving the ts doesn't create or re-generate the js file with any changes.

**Comment by derekcicerone** [comment]
Have you enabled the TypeScript builder for the project in which you'd like to have compile-on-save functionality?

**Comment by PDSBGreg** [comment]
Yup. Right now when I right click on the project and expand Configure, it says "Disable TypeScript Builder".

**Comment by derekcicerone** [comment]
Hmm, sorry, not sure in that case. If the project settings have compile on save enabled it should be working. Perhaps you could share a screenshot of the project settings?

**Comment by PDSBGreg** [comment]
Maybe that's the problem. I don't see a Compile on save option in the settings. I only have Compile all TypeScript files on build option.
![prefs](https://cloud.githubusercontent.com/assets/10424675/10764971/09d26bb2-7ca7-11e5-817d-c09e3efccb04.png)

**Comment by derekcicerone** [comment]
Hmm, that looks correct to me. Maybe check the error log for errors.

**Comment by PDSBGreg** [comment]
No errors in the log. I guess I'll just have to rebuild the entire project to get the updated JS files.

**Comment by derekcicerone** [comment]
Sorry I can't be of more assistance. We use this functionality in several projects here so it definitely works. Sounds like something is off but its tough to diagnose remotely.

**Comment by PDSBGreg** [comment]
No problem. Thanks for your attempts.
