### ISSUE TITLE
Import statement with jspm

### ISSUE THREAD

**Issue by xmehaut** [palantir/eclipse-typescript#289]
Hello
I used to use jspm in my react typescript projects. I installed for instance react, react-dom, bootstrap, material-ui succesfully, and i.m able to import them in my ts files with import statement.
Unfortunately, for some packages like react toolbox which successfully downloads with jspm too, i.m unable to import these libraries in the project. 
In the same way, il i use a sub reference in for instance material-ui like import {ThemeDecorator} from 'material-ui/styles'' it does'nt work too.
Could you explain me how the eclipse plugin try to find references for js libraries? And give me a hint to perform the above tasks?
Best regards
Ps : it is a very nice plugin! Which is better in my sense than the webstorm or vs ones

**Comment by derekcicerone** [comment]
The plugin resolves references via the built-in TypeScript language services support. Basically, the plugin finds all the .ts and .tsx files within the source folders of a project and sends them all into TypeScript language services. The service then resolves things.

**Comment by xmehaut** [comment]
Thanks
But when importing for instance react which is not a ts or tsx file but a js file found in the the jspm repository? How does it do?

Envoyé de mon iPhone

**Comment by derekcicerone** [comment]
JavaScript files are not passed into TypeScript so they aren't included. I believe newer versions of TypeScript may be able to ingest JS, but the version currently available does not.

**Comment by xmehaut** [comment]
Oki
Last mail :)
So if the react library is a js library and that the import * as React from 'react' works, it is because there were a ///reference ... To a d.ts file before. Is it right?

Envoyé de mon iPhone

**Comment by derekcicerone** [comment]
Yeah - if there is a d.ts file anywhere in the project with the definitions for React than that would work. Definition files are not loaded by path typically. (For our projects we typically put them all in a typings directory)

**Comment by xmehaut** [comment]
thanks

I put also my d.ts files in the typings directory which is created when i
use automatically  while using tsd,  The js library are loaded in my case
through jspm with a" jspm install react" command for instance into the
jspm_packages directory/npm or github

it is quite convenient and easy to use (excepted when i don't understand
for some packages why it is not working in ts ;) )

best regards

2015-11-11 17:25 GMT+01:00 Derek Cicerone <notifications@github.com>:
