### ISSUE TITLE
Merging palantir and typecs plugins in one

### ISSUE THREAD

**Issue by xmehaut** [palantir/eclipse-typescript#290]
Hello
Lack of ressources is always a pb in plugin dev. Why not conjuging efforts between palantir and typecs teams to build a more complete typescript plugin?

Best regards

**Comment by derekcicerone** [comment]
No strong reason - just never a priority for us.

**Comment by xmehaut** [comment]
One reason could be the debugging they do

Envoyé de mon iPhone

**Comment by derekcicerone** [comment]
You could switch to their plugin in that case, no? It might offer a superset of the functionality in this one.

**Comment by xmehaut** [comment]
The mix of the two plugins dob´t work well :(. . I switch to vs in that case if i need it, but it is not convenient

Envoyé de mon iPhone

**Comment by derekcicerone** [comment]
Oh sorry, I meant you could consider entirely switching to the other one if it has better functionality.
