### ISSUE TITLE
Cannot find documentation how to get started

### ISSUE THREAD

**Issue by jpsw** [palantir/eclipse-typescript#291]
I have an eclipse/maven webapp with js/jquery/ajax frontend and REST/json/spring-boot backend.

Was planning to try convert the js files to typescript files,
and installed nodejs and the palantir-typescript plugin from eclipse-marketplace.

Now, what do I do to get eclipse recognize tcs-files?

I tried to just create a tsc-file in the same place where I have the js files.
But Eclipse just treats it as a textfile without any syntax-highlights or tsc-compilation occurring.

Cannot find any docs how to get started on this?
Is there a guide somewhere?

**Comment by derekcicerone** [comment]
Ah yeah sorry, not much documentation. Basically just add .ts files into an Eclipse project, then enable TypeScript support by right-clicking on the project and enabling the TypeScript builder in the options (look in the "Configure" menu).

**Comment by jpsw** [comment]
Aah, that was the secret trick!
It works, thanks :)

**Comment by derekcicerone** [comment]
Cool :)

**Comment by basarat** [comment]
> Aah, that was the secret trick!

Documented already : https://github.com/palantir/eclipse-typescript#installation :rose:
