### ISSUE TITLE
Error markers disappear after a few seconds.

### ISSUE THREAD

**Issue by ilazarte** [palantir/eclipse-typescript#292]
Using a simple class like so, the error markers disappear after a few seconds despite the bad invocation to the method.  Is this a setting I've missed somewhere which removes markers?  

You can trigger this issue by adding a digit to the number argument.  The error marker appears, then after you hit save, the error marker disappears for me in a few seconds.

    class Derp {
        constructor() {
            this.hello(3);
        }
    
      hello(msg: string) {
           console.log(msg); 
        }
    }

**Comment by derekcicerone** [comment]
Thanks for the but report. Sorry, just wanted to give a heads-up that it might be a while until I can get to this but I'll do my best.

**Comment by derekcicerone** [comment]
Just tried this locally and I'm not able to reproduce the behavior. Once I hit save the marker remains. Which version of Eclipse are you using? Can you share a screenshot of the TypeScript property pane for the project containing the TypeScript file?

**Comment by ilazarte** [comment]
I'm on Eclipse Mars the latest.  I can't get a screenshot right now, but I can tell you that it understood the class definition.

**Comment by derekcicerone** [comment]
Oh, do you have the TypeScript builder enabled for the project?

**Comment by ilazarte** [comment]
Ah, that was it!  With Typescript builder enabled it works as expected.  Is it required in docs?  I didn't enable it because I thought it was optional.  Closing, and thanks.

**Comment by derekcicerone** [comment]
Its optional but my guess is most users would want it on. Feel free to submit a PR to remove the "(optional)" part...
