### ISSUE TITLE
TYpescript 1.7 support

### ISSUE THREAD

**Issue by xmehaut** [palantir/eclipse-typescript#293]
Hello,

I've just updated my eclipse typescript environment with th 1.7 version, and then, when i try to configure compiler options (Preferences/typescript/compiler) , I get the following messages avoiding me to configure the options:
"The currently displayed page contains invalid values"

any clue?

**Comment by derekcicerone** [comment]
Good catch, thanks for the report!

**Comment by xmehaut** [comment]
you're welcome...
Furthermore, it seems that the new exponentiation does'nt work, even if we
check the "Enable experiment support for ES7" feature in the parameter
window... Any clue?

regards
Xavier

2015-12-01 17:32 GMT+01:00 Derek Cicerone <notifications@github.com>:

**Comment by derekcicerone** [comment]
Just tried out the exponentiation support and it works fine (just inserts Math.pow). Wanna open a new issue for that with the code that isn't working?

**Comment by xmehaut** [comment]
rehi :)
I thought the new exponentation feature would avoid to insert Math.pow ?
Actually, where do you insert it?

2015-12-02 17:53 GMT+01:00 Derek Cicerone <notifications@github.com>:

**Comment by derekcicerone** [comment]
I think it turns something like:
```
var foo = 8 ** 3;
```
into:
```
var foo = Math.pow(8, 3);
```

**Comment by xmehaut** [comment]
oki , thanks :)

2015-12-02 17:57 GMT+01:00 Derek Cicerone <notifications@github.com>:
