### ISSUE TITLE
Propagating props doesn.t work in react tsx

### ISSUE THREAD

**Issue by xmehaut** [palantir/eclipse-typescript#299]
Hello
I.m facing an error when i try to propagates props in a component child, for instance by making 
       <MySubComponent {...this.props}   //and so on...

Any clue?

(I use the latst version of the plugin and types ript 1.7.5)

**Comment by derekcicerone** [comment]
I think this might be a good question for the Typescript team. The plugin is just a wrapper of the Typescript language services 1.7 functionality.

**Comment by xmehaut** [comment]
Hi Derek
I opened an issue on typescript github, and they told me to open an issue there :(
Best regards
Envoyé de mon iPhone

**Comment by derekcicerone** [comment]
ok, looks like this one:
https://github.com/Microsoft/TypeScript/issues/6115

I commented on the issue because I'm not sure how this could be fixed in the Eclipse plugin other than potentially updating to 1.8 (which is currently unsupported).

**Comment by xmehaut** [comment]
mea culpa :(
It actually works... What I did it was to port a javascript code into
typescript... but I forgot that typescript makes a types checking even on
the {...this.props} statement, i.e. the props which have to be destructured
into the component are checked to see if the attributes are compatible to
the ones the component accepts.... What was accepted in javascript, was not
anymore in typescript...for safe...
It is a good case to show that we may make unsafe code in javascript...

sorry for the inconvenience
xavier

2015-12-17 7:45 GMT+01:00 Derek Cicerone <notifications@github.com>:

**Comment by derekcicerone** [comment]
Cool, glad to hear you figured it out!

**Comment by xmehaut** [comment]
Hello Derek,

by the way, and out of the scope of this issue, is there a way to use in
the plugin  some of features which don't require compiler flags adding. I
have in mind the literal string useful feature (let toto : "toto") ?  This
feature is already available in typescript@next, and I thought that , as
you call the node typescript compiler directly, it could be available
directly in the  plugin... It don't seems the case... Could it be possible?

best regards
xavier

2015-12-17 8:34 GMT+01:00 Derek Cicerone <notifications@github.com>:

**Comment by derekcicerone** [comment]
If typescript@next is the develop branch then its currently not supported by the plugin but I could sync it up to the develop branch if you like. Normally I do this but I just didn't get around to it for 1.8 yet. Lemme know!

**Comment by xmehaut** [comment]
with pleasure :)

2015-12-18 16:52 GMT+01:00 Derek Cicerone <notifications@github.com>:

**Comment by derekcicerone** [comment]
The develop release has now been updated to the latest master TypeScript code. This should be roughly equivalent to the @next releases. Please note that the develop releases are unsupported since the TypeScript code is still under active development (so there are likely bugs that aren't on the plugin side).

**Comment by xmehaut** [comment]
Thanks a lot Derek... I'm going right now to update eclipse with...
best regards

2015-12-21 19:48 GMT+01:00 Derek Cicerone <notifications@github.com>:
