### ISSUE TITLE
No compilation error on a weird line.

### ISSUE THREAD

**Issue by Rouche** [palantir/eclipse-typescript#311]
Hi,

I have this line wich by mistake took from a javascript code buit forgot to add "="

public require: "ngModel";

It compiles ok (Im pretty sure it should not), and the line is not in the corresponding .js!
Is it a Eclipse plugin bug or a TypeScript? Is there a way to configure the plugin to show those errors?

Thanks.

**Comment by derekcicerone** [comment]
I believe this is controlled by TypeScript itself. The Eclipse plugin doesn't really dig into the contents of the source files directly.
