### ISSUE TITLE
Auto Complete with Interfaces

### ISSUE THREAD

**Issue by mashleyttu** [palantir/eclipse-typescript#312]
Hi, It would be great if you supported auto completion for interfaces. For example,

```
interface test {
   x : number,
   y : string 
}

let t : test = {
  //Ctrl+Space at this point doesn't display available variables x or y
}
```

Thanks for your consideration!
Matt

**Comment by derekcicerone** [comment]
This plugin is just a pass-through for support in TypeScript itself. If this isn't currently supported please file an issue on the TypeScript project.
