### ISSUE TITLE
Matching bracket color

### ISSUE THREAD

**Issue by Rouche** [palantir/eclipse-typescript#313]
Hi,

I just want to know what color / system variable the TypeScript editor "matching bracket" color is using. I really want to change it because i use black theme.
![2016-04-19_8-01-43](https://cloud.githubusercontent.com/assets/1267438/14638781/fc11443c-0606-11e6-80ea-dbfcddbcd370.png)
I tryed everything.

General->Editors->Text Editors->Annotations->Matching tags : Not working
General->Editors->Structured Text Editor->Matching brackets highlight : Not working
Javascript->Editor->Matching brackets highlight : Not working
Java->Editor->Matching brackets highlight : Not working (of course)

Theres also another one defined in plugin.xml of org.eclipse.jdt.ui
I overriden this color too. And yeah not working either.
```
<colorDefinition
    id="org.eclipse.jdt.ui.matchingBracketsColor"
    isEditable="false"
    label="%Dummy.label"
    value="240,240,240">
</colorDefinition>
```

Edit:
I saw this line in IPreferenceConstants, should this line be changed to "org.eclipse.jdt.ui.matchingBracketsColor" ? It my screenshot this does not seem to be 128,128,128.
```
String EDITOR_MATCHING_BRACKETS_COLOR = "editor.matchingBracketsColor";
```
```
        store.setDefault(IPreferenceConstants.EDITOR_MATCHING_BRACKETS_COLOR, "128,128,128");
```

Thanks

**Comment by derekcicerone** [comment]
Ah yeah we should use the default - good call. Wanna submit a PR for this? I think you are looking at the correct code to change.

**Comment by Rouche** [comment]
Eek, well i was just checking code really fast.

Unfortunatelly im not setup as a plugin development to fully test it, it might take some time.
I will also dont understand where this property is used (editor.matchingBracketsColor), is it internally by Eclipse?

**Comment by derekcicerone** [comment]
I think its just internal to the plugin. I can also take a shot at this change but it might be a while - its hard for me to find time to develop lately.

**Comment by Rouche** [comment]
Its ok im trying to configure my environment. The project does not seem like the others ive seen. I dont see the "Maven Libraries" in classpath. Ill try tomorrow.

Regards

**Comment by Rouche** [comment]
Well i tryed a lot of stuff.

Using default keys in PreferenceConstants.EDITOR_MATCHING_BRACKETS
Changing default to "250,250,250"
Changing the preference key name. 
Disabling the feature completelly. (Obviously this one removes the feature and does not use the JDT)
Removing the 2 other stores in the ChainedPreferenceStore

Something seems to override the value and only for TypeScript editor. All others (Java, HTML, xml) are ok. TypeScript editor stays black. 
Or there is something missing in the configuration.

**Comment by derekcicerone** [comment]
cool :)
