### ISSUE TITLE
add fileExtension_ts to Marketplace entry

### ISSUE THREAD

**Issue by mickaelistria** [palantir/eclipse-typescript#321]
Eclipse Marketplace and Marketplace client in IDE recently added support for discovery of marketplace extensions for a given filetype. In order to get this plugin discovered by users opening *.ts files, it seems important to add the fileExtension_ts tag to the marketplace entry.

**Comment by mickaelistria** [comment]
@tomshen Do you have permission to update https://marketplace.eclipse.org/content/typescript ? If not and if you cannot join the original author, you can send a mail to marketplace administrators to perform this change.

**Comment by tomshen** [comment]
I currently don't have permissions, but I've requested a transfer of ownership. I'll add the tag once I get ownership.

**Comment by tomshen** [comment]
Done! I also added fileExtension_tsx.

**Comment by mickaelistria** [comment]
Thanks. I hope many Eclipse user will more easily discover this nice plugin!
