### ISSUE TITLE
Support to recognize Imports mapped via Package Managers (SystemJS)

### ISSUE THREAD

**Issue by JustinCIS** [palantir/eclipse-typescript#324]
Hi All,

I have been working in Angular2 as of late, and SystemJS (and other package managers) are fairly prevalent while leveraging the Framework.

I was wondering if there was any way to configure the Typescript Editor to factor in libraries mapped through a package manager, such as SystemJS.  

When I perform the following:

`import {Component} from '@angular/core';`

the Typescript Editor is raising "Cannot find module" despite the fact that it resides in node_modules - and dynamically loaded in via SystemJS (systemjs.config.js).

Any plans to support these type of imports in the future?

**Comment by tomshen** [comment]
This should have been fixed in https://github.com/palantir/eclipse-typescript/pull/309. Could you try adding the library (e.g. "node_modules/@angular/core") to your sources?

**Comment by JustinCIS** [comment]
Ahhh!

So I ended up adding the node_modules directory along with my app directory as Source folder(s), (e.g. "app, node_modules") and it appears to have fixed my issue.

Thanks tomshen!

**Comment by JustinCIS** [comment]
Okay, so I discovered a caveat to this solution.  There appears to be a conflict by adding the node_modules directory as a Source folder when paired with the "Compile all TypeScript files on build" option.  No .js files are generated until I remove the node_modules directory as a Source.  

Do I need to open a new issue for this?  

Thanks again!

**Comment by tomshen** [comment]
Does adding just `node_modules/@angular/core` (instead of all of `node_modules`) as a source work?

**Comment by JustinCIS** [comment]
I wouldn't feel it would be practical for my particular case as I would then have to add every referenced library from node_modules as a Source (i.e. - `import {bootstrap} from '@angular/platform-browser-dynamic';`, `import { Http, Response } from '@angular/http';`, `import { PrimeNG } from 'primeng/primeng';` etc.)

**Comment by tomshen** [comment]
You should only need to do that for libraries that ship with their own libraries, but that's definitely not a good user experience. Could you close this issue and file another one with the specific caveat that you found?

**Comment by JustinCIS** [comment]
Sounds good.  

Thank you for your input!
