### ISSUE TITLE
typescript to javascript compilation not working in Eclipse Mars

### ISSUE THREAD

**Issue by Kiran-N** [palantir/eclipse-typescript#329]
I am using Eclipse mars, I installed the plugin and enable typscript bulilder. I gave path to my node.exe in the typscript configuration. When I save the .ts file it is not converting in to .js . Please suggest.

**Comment by shawsoft** [comment]
I tried exactly the same was as Kiran-N and it didn't work for me either. 
In fact the plugin hangs trying to build my project.

**Comment by shawsoft** [comment]
![palantir_nodejs_crash](https://cloud.githubusercontent.com/assets/12120833/19626996/eda2f74a-993d-11e6-84d3-2f7f9a691583.GIF)

**Comment by shawsoft** [comment]
My problem seems to be that it is crashing in the middle of node_modules. Is there a .ignore file that can be used to ignore node_modules and just look at my code?
