### ISSUE TITLE
Duplicate identifier

### ISSUE THREAD

**Issue by ghost** [palantir/eclipse-typescript#75]
I just installed the plugin and there are more than 100 errors sayin duplicate identifier on the latest jquery.d.ts definition file. See image attached below:

![image](https://f.cloud.github.com/assets/3502702/1175538/c1a4b0f6-215a-11e3-9792-7cb01b024042.png)

**Comment by Amenel** [comment]
For anyone who meets the same issue and who comes here for a solution: for me, this error occurred after I had just installed the plugin (1.8.0v20160504) and enabled the TypeScript nature on the project, until I configured the "source" and "exported" folders in the properties of the project.
